export const ASSET_TYPE_COIN = 'COIN';
export const ASSET_TYPE_TOKEN = 'TOKEN';

export const CHAIN_LIST_MAP = {
    ALL: ['eth', 'bsc', 'polygon', 'tron','solana'],
    BSC: ['bsc'],
    ETH: ['eth'],
    POLYGON: ['polygon'],
    TRON: ['tron'],
    SOLANA: ['solana']
};
export const CHAIN_ID_MAP = {
    ETH: 1,
    BSC: 56,
    POLYGON: 137,
    TRON: 999,
    ARB: 42161,
    BTTC: 199,
    SOLANA: 900,
};
export const CHAIN_ID_TYPE_MAP = {
    1: 'ETH',
    56: 'BSC',
    137: 'POLYGON',
    999: 'TRON',
    199: 'BTTC',
    42161: 'ARB',
    900: 'SOLANA',
};
export const CHAIN_TO_SYMBOL_MAP = {
    ETH: 'ETH',
    BSC: 'BNB',
    POLYGON: 'MATIC',
    TRON: 'TRX',
    ARB: 'ARB',
    BTTC: 'BTTC',
    SOLANA: 'SOL',
};
export const btc = {
    order: 0,
    symbol: 'BTC',
    name: 'Bitcoin',
    id: 'bitcoin',
    chain: 'BTC',
    chainType: 'BTC',
    type: ASSET_TYPE_COIN,
    decimals: 8,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
};
export const eth = {
    order: 1,
    symbol: 'ETH',
    name: 'Ethereum',
    id: 'ethereum',
    chain: 'ETH',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
};
export const bsc = {
    order: 5,
    symbol: 'BNB',
    name: 'Binance Coin',
    id: 'binancecoin',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png',
};
export const polygon = {
    order: 6,
    symbol: 'MATIC',
    name: 'Matic',
    id: 'matic-network',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
};
export const tron = {
    order: 7,
    symbol: 'TRX',
    name: 'Tron',
    id: 'tron',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
};
export const solana = {
    order: 8,
    symbol: 'SOL',
    name: 'Solana',
    id: 'solana',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_COIN,
    decimals: 9,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
};
export const duku_erc20 = {
    order: 2,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const duku_bep20 = {
    order: 3,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};

export const mxgs = {
    order: 9,
    symbol: 'MXG',
    name: 'Meta X Gold',
    id: 'mxg',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '5Rn5TGpwsizxGsynsfv8hBAQvX1kfZcGWJDTNmGtx9K8',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.ibb.co/HhVYLhr/MX-GOLD-COIN.png',
};
export const xusdts = {
    order: 10,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 9,
    contract: 'CAwhZLDxHVVuKDYrxpYHsTg3Y3ABNmix4e2oW2Ududa4',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.ibb.co/QnsNXMx/xusdt2.png',
};
export const usdts = {
    order: 11,
    symbol: 'USDT',
    name: 'USDT',
    id: 'usdt',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 9,
    contract: 'BYWJf12T68EktxZuUZqnh1bBEojGkUf95rvnoLxJfVQh',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.ibb.co/D7W3ZWZ/usdt2.png',
};
export const btcs = {
    order: 12,
    symbol: 'BTC',
    name: 'BTC',
    id: 'btc',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '3b7uqjyw9gxoaM6EJpBYE3ee93cfAbtNUAvZ5iof1RqF',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
};
export const eths = {
    order: 13,
    symbol: 'ETH',
    name: 'ETH',
    id: 'eth',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '3c8jjrxrVcGERxboVVKDhBzHHWgYB6BfZuwSdhpuJELL',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.pinimg.com/originals/49/d1/0c/49d10cb0a3c978475a49f239e4e2f060.png',
};
export const ltcs = {
    order: 14,
    symbol: 'LTC',
    name: 'LTC',
    id: 'ltc',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: 'C7za45teP96BQEbRXgQi5bGN4gVM2iqo3z41rpFPdh4a',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
};
export const doges = {
    order: 15,
    symbol: 'DOGE',
    name: 'DOGE COIN',
    id: 'doge',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '7XraejVhjM1qrzpqfDfuSu9ZqxQvZbKLDDDPc5c3wfQD',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2HxwuBXfjRHOAOGPrbyeJenImodJp68tow&s',
};
export const xusdt = {
    order: 12,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: 'TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const xusdtp = {
    order: 13,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x071bf943E0069d4CE12d84CFc6821f8A4688a542',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const xusdtb = {
    order: 14,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xebC818505c9a2D94eC5827967390F379c55a929a',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const mxg = {
    order: 15,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: 'TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const mxgp = {
    order: 16,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x00c73D3F236D6fb1bA4ce2bbB4358A16ba51612B',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const mxgb = {
    order: 17,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x7dB8b3b7C313f9385458b357eA569aEd0552580D',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const usdtb = {
    order: 18,
    symbol: 'USDT',
    name: 'Binance Pegged USDT',
    id: 'tether-pulsechain',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x55d398326f99059fF775485246999027B3197955',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/200x200/825.png',
};
