export const ASSET_TYPE_COIN = 'COIN';
export const ASSET_TYPE_TOKEN = 'TOKEN';

export const CHAIN_LIST_MAP = {
    ALL: ['eth', 'bsc', 'polygon', 'tron','solana'],
    BSC: ['bsc'],
    ETH: ['eth'],
    POLYGON: ['polygon'],
    TRON: ['tron'],
    SOLANA: ['solana']
};
export const CHAIN_ID_MAP = {
    ETH: 1,
    BSC: 56,
    POLYGON: 137,
    TRON: 999,
    ARB: 42161,
    BTTC: 199,
    SOLANA: 900,
};
export const CHAIN_ID_TYPE_MAP = {
    1: 'ETH',
    56: 'BSC',
    137: 'POLYGON',
    999: 'TRON',
    199: 'BTTC',
    42161: 'ARB',
    900: 'SOLANA',
};
export const CHAIN_TO_SYMBOL_MAP = {
    ETH: 'ETH',
    BSC: 'BNB',
    POLYGON: 'MATIC',
    TRON: 'TRX',
    ARB: 'ARB',
    BTTC: 'BTTC',
    SOLANA: 'SOL',
};
export const btc = {
    order: 0,
    symbol: 'BTC',
    name: 'Bitcoin',
    id: 'bitcoin',
    chain: 'BTC',
    chainType: 'BTC',
    type: ASSET_TYPE_COIN,
    decimals: 8,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
};
export const eth = {
    order: 1,
    symbol: 'ETH',
    name: 'Ethereum',
    id: 'ethereum',
    chain: 'ETH',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
};
export const bsc = {
    order: 5,
    symbol: 'BNB',
    name: 'Binance Coin',
    id: 'binancecoin',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png',
};
export const polygon = {
    order: 6,
    symbol: 'MATIC',
    name: 'Matic',
    id: 'matic-network',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
};
export const tron = {
    order: 7,
    symbol: 'TRX',
    name: 'Tron',
    id: 'tron',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_COIN,
    decimals: 18,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
};
export const solana = {
    order: 8,
    symbol: 'SOL',
    name: 'Solana',
    id: 'solana',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_COIN,
    decimals: 9,
    contract: null,
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
};
export const duku_erc20 = {
    order: 2,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'ETH',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const duku_bep20 = {
    order: 3,
    symbol: 'DUKU',
    name: 'KUKU DOLLAR',
    id: 'duku',
    chain: 'BSC',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xBf9CF55bCf5b3A6e3A5560d897D2eA17908F7D00',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://dukuwallet-2aeb92c5caa8.herokuapp.com/content/kuku_dollar.png',
};
export const slx = {
    order: 4,
    symbol: 'SLX',
    name: 'Solana X',
    id: 'slx',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 9,
    contract: 'DDNuH16bNVrzYMeLHztQgc3LDVMSasoeuF8zi8XNTQrh',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.ibb.co/GC5VBgq/SLX-COIN-241209.png',
};
export const mxgs = {
    order: 9,
    symbol: 'JYB',
    name: 'Jin Yuanbao (Solana X)',
    id: 'mxg',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '5Rn5TGpwsizxGsynsfv8hBAQvX1kfZcGWJDTNmGtx9K8',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.postimg.cc/0yP8wdJS/MX-GOLD-COIN.png',
};
export const xusdts = {
    order: 10,
    symbol: 'XUSDT',
    name: 'Tether AC (Solana X)',
    id: 'xusdt',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 9,
    contract: 'CAwhZLDxHVVuKDYrxpYHsTg3Y3ABNmix4e2oW2Ududa4',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.postimg.cc/2yWz40wQ/xusdt2.png',
};
export const usdts = {
    order: 11,
    symbol: 'USDT',
    name: 'Tether AC (USDT Solx)',
    id: 'usdt',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 9,
    contract: 'BYWJf12T68EktxZuUZqnh1bBEojGkUf95rvnoLxJfVQh',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.postimg.cc/KzRcYG3s/usdt2.png',
};
export const btcs = {
    order: 12,
    symbol: 'BTC',
    name: 'Bitcoin (Solana X)',
    id: 'btc',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '3b7uqjyw9gxoaM6EJpBYE3ee93cfAbtNUAvZ5iof1RqF',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
};
export const eths = {
    order: 13,
    symbol: 'ETH',
    name: 'Ethereum (Solana X)',
    id: 'eths',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '3c8jjrxrVcGERxboVVKDhBzHHWgYB6BfZuwSdhpuJELL',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://i.pinimg.com/originals/49/d1/0c/49d10cb0a3c978475a49f239e4e2f060.png',
};
export const ltcs = {
    order: 14,
    symbol: 'LTC',
    name: 'Litecoin (Solana X)',
    id: 'ltc',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: 'C7za45teP96BQEbRXgQi5bGN4gVM2iqo3z41rpFPdh4a',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
};
export const doges = {
    order: 15,
    symbol: 'DOGE',
    name: 'DOGE COIN (Solana X)',
    id: 'doge',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '7XraejVhjM1qrzpqfDfuSu9ZqxQvZbKLDDDPc5c3wfQD',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf2HxwuBXfjRHOAOGPrbyeJenImodJp68tow&s',
};
export const usdcs = {
    order: 16,
    symbol: 'USDC',
    name: 'USDC (Solana X)',
    id: 'usdc',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '4mTty3JfcuYHhHQNojf66bxpReHwQcBMDwAwQoNAuHqh',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://cryptologos.cc/logos/usd-coin-usdc-logo.png',
};
export const xusdt = {
    order: 12,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: 'TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const xusdtp = {
    order: 13,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x071bf943E0069d4CE12d84CFc6821f8A4688a542',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const xusdtb = {
    order: 14,
    symbol: 'XUSDT',
    name: 'XUSDT',
    id: 'xusdt',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0xebC818505c9a2D94eC5827967390F379c55a929a',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TAZ1dbBfBCELD49obL3Agh9GtYVrp3jkJL.png?t=1715415057068',
};
export const mxg = {
    order: 15,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'TRON',
    chainType: 'TRON',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: 'TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const mxgp = {
    order: 16,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'POLYGON',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x00c73D3F236D6fb1bA4ce2bbB4358A16ba51612B',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const mxgb = {
    order: 17,
    symbol: 'MXG',
    name: 'META X GOLD',
    id: 'mxg',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x7dB8b3b7C313f9385458b357eA569aEd0552580D',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI:
        'https://static.tronscan.org/production/upload/logo/new/TS3kGJaXyvVnWLVgM62izS24h2P9XhRE1S.png?t=1715938900758',
};
export const usdtb = {
    order: 18,
    symbol: 'USDT',
    name: 'Binance Pegged USDT',
    id: 'tether-pulsechain',
    chain: 'BSC',
    chainType: 'EVM',
    type: ASSET_TYPE_TOKEN,
    decimals: 18,
    contract: '0x55d398326f99059fF775485246999027B3197955',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s2.coinmarketcap.com/static/img/coins/200x200/825.png',
};

export const amzn = {
    order: 19,
    symbol: 'AMZN',
    name: 'Amazon.com Inc',
    id: 'amzn',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: 'E29pZ9m3UgjfCcbsm75o92DRJFEzSCHdJMg7RatGXMxE',
    mnemonic: null,
    privateKey: '64BipJRmh1NdDMGtGxUPg42HNKxBfXX1fw3H7jMmsmoVY1mTT626sLTJqDbwtNMDFvaWKhVftjNx1wKhvGLKPM9r',
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
};

export const goog = {
    order: 20,
    symbol: 'GOOG',
    name: 'Alphabet Inc Class C',
    id: 'goog',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '5r1q11V283MoqGHG6YJoyajBAjdQk1YypS4xQx6waT34',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://s3-symbol-logo.tradingview.com/alphabet--600.png',
};

export const tsla = {
    order: 22,
    symbol: 'TSLA',
    name: 'Tesla Motors Inc',
    id: 'tsla',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: 'Dvk7VTh5NN4qwNux3YCdMfPsULWVopXCSG8uwNbYaqN9',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_Motors.svg/1200px-Tesla_Motors.svg.png',
};

export const aapl = {
    order: 21,
    symbol: 'AAPL',
    name: 'Apple Inc',
    id: 'aapl',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '8xWdpHtw4jmDwHK5pMtN2gzwPaR89tNbGaMHNNpjnTR3',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?201609051049',
};

export const cnyusd = {
    order: 23,
    symbol: 'cnyusd',
    name: 'Chinese Yuan',
    id: 'cnyusd',
    chain: 'SOLANA',
    chainType: 'SOLANA',
    type: ASSET_TYPE_TOKEN,
    decimals: 6,
    contract: '4LTu6v4zrVFJDVyok5iK9nAdyX6chDNGumMu6vRwKi42',
    mnemonic: null,
    privateKey: null,
    walletAddress: null,
    balance: 0,
    unconfirmedBalance: 0,
    value: 0,
    price: 0,
    active: true,
    logoURI: 'https://responsive.fxempire.com/v7/_fx-ui-mfe_/currencies/production/usd-cny.svg',
};

export const stockListSymbols =  ['AAPL', 'GOOG', 'TSLA', 'AMZN'];

export const forexListSymbols = ['CNYUSD'];